apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-volume-setup-role
  namespace: storage
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    app: longhorn-volume-setup
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "create"]
