apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-volume-setup
  namespace: storage
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn-volume-setup-role
subjects:
  - kind: ServiceAccount
    name: longhorn-volume-setup
    namespace: storage
